import SEO from "@/components/SEO";

export default function Privacy() {
  return (
    <>
      <SEO
        title="Privacy Policy — 8Twelve Mortgage Corp."
        description="8Twelve Mortgage Corp. Privacy Policy governing the collection, use, and disclosure of personal information."
        canonical="/privacy"
      />
      <section className="container-page pt-16 pb-6">
        <p className="text-xs uppercase tracking-widest text-gold font-medium">Compliance</p>
        <h1 className="mt-3 text-4xl md:text-5xl font-serif">Privacy Policy</h1>
        <p className="mt-4 text-sm text-muted-foreground">
          8Twelve Mortgage Corp. — Brokerage Licence #13072 · Last updated December 2022
        </p>
      </section>

      <article className="container-page pb-24 max-w-4xl space-y-10 text-[15px] leading-relaxed text-foreground/85">
        <Section title="8Twelve Mortgage Privacy Policy">
          <p>
            8Twelve Mortgage Corp. ("8Twelve") helps customers find the most suitable mortgage, loan or credit facility,
            and/or other related products and services like insurance that we may offer.
          </p>
          <p>
            At 8Twelve, we know that the protection of your privacy is important to you. For this reason, we have taken
            steps to ensure that any personal information that you provide to 8Twelve is protected by a range of robust
            business procedures and rigorous security safeguards to ensure that your information is kept confidential and
            used only for the purposes detailed in this Privacy Policy. This Privacy Policy is intended to establish
            responsible and transparent practices for the management of personal information and to satisfy the
            requirements of rules established by the Personal Information Protection and Electronic Documents Act
            (PIPEDA), and similar provincial laws from Quebec, Alberta and B.C.
          </p>
        </Section>

        <Section title="Application and Scope">
          <p>
            This Privacy Policy generally applies to any personal information collected or generated by 8Twelve, its
            brokers or anyone acting as an agent on our behalf ("Authorized Agent"), from or about its customers and
            other individuals with whom it deals, which may include potential customers as well as any other additional
            person named on an account, in any form. At any time that you do business with 8Twelve, participate in a
            contest or promotion run by 8Twelve, a 8Twelve broker or with an Authorized Agent, or interact with us in any
            manner, you are protected by the rights and safeguards contained in this Privacy Policy and you explicitly
            agree to its terms.
          </p>
          <p>
            This Privacy Policy also governs personal information collected about 8Twelve's website users and explains
            how we use and disclose personal information that we collect from users who visit our website and otherwise
            interact with us through www.8twelve.mortgage ("website"). It also explains how we use cookies and similar
            technologies.
          </p>
        </Section>

        <Section title="Definition of Personal Information">
          <p>
            When used in this Privacy Policy, personal information means "any information about an identifiable
            individual". This may include, for example, your name, contact information, email address, information
            relating to your account with us, including your identity and the mortgage you take out, as well as your
            credit and banking information, billing records and any complaints documented in a file. It may also include
            other types of more technical information when you interact with us through our website, when this
            information can identify you as an individual. Personal information that is aggregated and cannot be
            associated with an identifiable individual is not considered to be personal information.
          </p>
        </Section>

        <Section title="Collection and Use of Personal Information">
          <p>We collect most of our information about you directly from you, with your consent.</p>
          <p>
            We usually collect your name, address, phone number(s), email address, occupation, employer's name, birth
            date, annual income, net worth, assets, liabilities, credit history, investment objectives, banking
            information, as well as other account and payment information, including information pertaining to your use
            of our products and services when you register to 8Twelve services. We may also collect other information
            such as your social insurance number, driver's license or passport number, when required and/or authorized by
            law.
          </p>
          <p>
            We may also obtain information about you from third parties, with your consent. For example, for credit
            evaluation purposes, we may need to determine your creditworthiness through contact with an independent credit
            reporting agency or another source.
          </p>
          <p>
            8Twelve generally collects personal information to: confirm and authenticate customer identity; determine
            eligibility for products and services; process applications and provide products or services; monitor and
            improve customer service; create and administer mortgage financing and accounts; meet legal, regulatory and
            contractual requirements; understand customer needs to improve and develop products; and provide
            personalized offers subject to your consent.
          </p>
        </Section>

        <Section title="Your Consent">
          <p>
            8Twelve obtains consent from the individuals concerned for the collection, use or disclosure of personal
            information through various means. The most common method we use to obtain a customer's consent is by way of
            consent forms. Where practicable, we may also obtain consent through electronic communications or other
            written documentation.
          </p>
          <p>
            In certain exceptional circumstances, personal information may be collected, used or disclosed without
            consent, including:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>
              when information is being collected, used or shared for the detection, prevention or remediation of a
              breach of agreement, fraud or other illegal activity, and the collection of consent might defeat the
              purpose of collecting the information;
            </li>
            <li>to collect a debt;</li>
            <li>
              to comply with a subpoena, warrant or other court order, or as may be otherwise required or authorized by
              law or by any regulatory bodies having jurisdiction.
            </li>
          </ul>
        </Section>

        <Section title="Right to Withdraw Consent">
          <p>
            Consent may be withdrawn at any time, subject to legal or contractual restrictions and reasonable notice.
            Depending on the circumstances, withdrawal or amendment of your consent may prevent us from providing you
            with 8Twelve's products and services. To opt-out of commercial emails, click the "unsubscribe" link at the
            bottom of any commercial electronic communication we send you. Please note that even if you opt-out of
            promotional communications, we may still need to contact you with information about your account.
          </p>
        </Section>

        <Section title="Sharing of Personal Information">
          <p>
            Your information may be made available within 8Twelve Mortgage and to Authorized Agents or service providers
            to fulfill the purposes for which it has been collected. 8Twelve will not sell, rent or trade your personal
            information to any third party. However, we may share your personal information when authorized by law or as
            follows: with financial institutions in connection with the administration of products and services; with
            credit reporting and assessment agencies, insurers or other lenders; with service providers and Authorized
            Agents (assessment agencies, real estate appraisers, insurance brokers, public registers, employers,
            collection agencies, professionals and affiliated companies) to deliver the services you've requested.
          </p>
          <p>
            We may have to share your personal information in special circumstances — for example in response to a legal
            request such as a subpoena, search warrant or court order — or in connection with a sale, merger,
            bankruptcy, sale of assets or reorganization of our company.
          </p>
        </Section>

        <Section title="Transfers of Personal Information Outside of Canada">
          <p>
            Some third party service providers may be located outside of Canada. In order to use these third-party service
            providers, we may transfer your personal information outside of Canada. When we do that, your personal
            information may be subject to foreign laws and potential access by law enforcement or other governmental
            agencies in those countries.
          </p>
        </Section>

        <Section title="Business Analytics">
          <p>
            We may share aggregated customers and/or website users' information with our partners or entities within
            8Twelve Mortgage. This information does not allow identifying individual customers nor users, and is only
            used to provide a better understanding of general customer profiles and industry trends.
          </p>
        </Section>

        <Section title="Website Privacy">
          <p>
            8Twelve collects and uses personal information from website visitors in the following ways:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>
              <strong>Inquiries.</strong> Name, contact information, email and any information you provide when you make
              an inquiry — used to respond to your request.
            </li>
            <li>
              <strong>Registration.</strong> Contact information you provide to receive electronic communications — you
              can unsubscribe at any time.
            </li>
            <li>
              <strong>Application forms.</strong> Information provided in mortgage, pre-qualification, refinancing or
              renewal applications. We do not require your SIN to accept an online application.
            </li>
            <li>
              <strong>Satisfaction surveys.</strong> Information you provide if you choose to participate, used to
              improve service levels.
            </li>
            <li>
              <strong>Technical information.</strong> IP address, browser, OS, screen resolution, location, referring
              site, search terms, pages viewed — collected via cookies and similar technologies to measure and improve
              the website.
            </li>
            <li>
              <strong>Google Analytics & AdWords Remarketing</strong> are used; you may opt out via Google's tools.
            </li>
            <li>
              <strong>Third-party advertising.</strong> Companies may use information about your visits to deliver
              relevant ads; you can opt out via the Digital Advertising Alliance of Canada at{" "}
              <a className="underline hover:text-gold" href="http://youradchoices.ca/" target="_blank" rel="noreferrer">youradchoices.ca</a>.
            </li>
            <li>
              <strong>Your choice with cookies.</strong> You can block cookies in your browser settings; some site
              functionality may be unavailable as a result.
            </li>
          </ul>
        </Section>

        <Section title="Mobile App Data Collection">
          <p>
            If you download or use any of our applications, we may collect information necessary to authenticate you and
            may record your IP geolocation. With your prior permission we may also collect location data, contacts,
            pictures and camera/photo library content to provide features of our service. You can enable or disable
            access at any time in your device settings.
          </p>
        </Section>

        <Section title="Quality and Access Rights">
          <p>
            8Twelve strives to ensure that personal information is accurate, complete and up-to-date. Customers may
            request access and may correct or amend inaccuracies by contacting us. 8Twelve has the right to refuse a
            request for access if the information is protected by legal privilege, would reveal confidential commercial
            information, was collected for fraud-detection purposes, or for other reasons authorized under applicable
            laws.
          </p>
        </Section>

        <Section title="Security of Personal Information">
          <p>
            We will use reasonable security measures to protect your personal information against unauthorized access.
            8Twelve has implemented administrative, technical and physical controls designed to safeguard your personal
            information. No method of transmission over the internet, or method of electronic storage, is 100% secure.
          </p>
        </Section>

        <Section title="Retention">
          <p>
            Personal information will be retained only as long as necessary for the fulfilment of the purposes for which
            it was collected and for which consent was received, or to satisfy legal requirements.
          </p>
        </Section>

        <Section title="How to Contact Us">
          <p>
            If you have questions, concerns or complaints regarding this Privacy Policy or the personal information that
            8Twelve has about you, or to withdraw consent (when applicable), please contact:
          </p>
          <div className="rounded-xl border border-border bg-card/70 p-5 text-sm">
            <p className="font-semibold text-foreground">8Twelve Mortgage Corp.</p>
            <p>55 Renfrew Dr, Suite 201, Markham, Ontario, Canada L3R 8H3</p>
            <p className="mt-2">
              By phone: <a className="underline hover:text-gold" href="tel:+16479921909">647-992-1909</a> or{" "}
              <a className="underline hover:text-gold" href="tel:+19055544332">905-554-4332</a>
            </p>
            <p>
              By email: <a className="underline hover:text-gold" href="mailto:amit.bhola@8twelve.mortgage">amit.bhola@8twelve.mortgage</a>
            </p>
          </div>
        </Section>

        <Section title="Change of Privacy Policy">
          <p>
            8Twelve will review and update its policies and procedures as required to keep current with rules and
            regulations, new technologies, standards and customer concerns. Our Privacy Policy may therefore change from
            time to time. We will post any privacy policy changes on our website and, if the changes are material, we
            will provide a more prominent notice. This Privacy Policy was last updated on December 2022.
          </p>
          <p className="text-sm text-muted-foreground">
            Both the English and French versions of our Privacy Policy have equal legal value.
          </p>
        </Section>
      </article>
    </>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-4">
      <h2 className="text-2xl md:text-3xl font-serif text-primary">{title}</h2>
      {children}
    </section>
  );
}
